### ISSUE TITLE
Ability to specific single or list of URLs in addition to sitemap.

### ISSUE THREAD

**Issue by seandunaway** [patrickmn/ocp#1]
I'm finding the use case to sometimes run ocp against a single URL (versus a sitemap).  I use wget but the -l option and others are nice.

**Comment by patrickmn** [comment]
Sounds good to me. Could be useful for scripting purposes too, i.e. something generates the "sitemap" (which isn't actually an XML sitemap) and OCP crawls it (with throttling, maxes, etc.)

**Comment by patrickmn** [comment]
This is included in the beta/release candidate for OCP 2.7 via the --urls parameter (e.g. ocp --urls foo.com/a foo.com/b):

http://files.patrickmylund.com/tools/ocp2/linux/ocp-2.7beta-i386.tar.gz
http://files.patrickmylund.com/tools/ocp2/linux/ocp-2.7beta-amd64.tar.gz
http://files.patrickmylund.com/tools/ocp2/windows/ocp-2.7beta.zip

If no issues are discovered, it'll become the official release.

Thanks!
