### ISSUE TITLE
pages sometimes not cached

### ISSUE THREAD

**Issue by graphicsxp** [patrickmn/ocp#4]
I have setup a cron to run the OCP program every 15 minutes. I can tell from my apache logs that the pages of my sitemap are being called.

However when I test my TimeToFirstByte with a tool like http://www.bytecheck.com/ , I can see that sometimes ages are not cached because the TFB is way too high. If I run it a second time then it is fast, meaning the page was cached by bytecheck's call, but not by OCP's call.

This is not consistent. Do you have an explanation or could you give me some clue as to why this happens ?

Thanks !

**Comment by patrickmn** [comment]
My guess is this is something unrelated to OCP. All OCP does is make HTTP requests to all the URLs in the sitemap. Perhaps it is loading too many pages at once (try running with -c 1)

Do you get any error output when you run OCP? (You can try running with the -v switch to verify that the URLs are actually being primed, but errors should show up regardless.)

**Comment by graphicsxp** [comment]
thanks for the reply. No errors :(  It's weird, I don't know what it could be.

**Comment by patrickmn** [comment]
What server software are you running? Perhaps these pages are being evicted from the cache. (Max number of cached pages, cache lifetime, etc. etc.) Or perhaps bytecheck is making a different kind of request, and the server software isn't serving the cached page for some reason.

Unfortunately I'm not sure there's much you can do on the OCP side.
